# nothing

name: Update regularly every hour

# daily job
on:
    push:
    schedule:
        -
            cron: 00 00 5,10,15,20,25,30 * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            -
                uses: actions/checkout@v2
            # Record (use record.sh or record2.sh)
            -
                name: run
                run: |
                    sh ./start.sh
